- hosts: all

- name: Install required packages
  ansible.builtin.import_playbook: setup.yml

- name: Deploy application
  ansible.builtin.import_playbook: deploy.yml

- name: Run datadog
  ansible.builtin.import_playbook: datadog.yml