- hosts: webservers
  become: yes

  pre_tasks:
  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes

  roles:
    - role: geerlingguy.pip
      tags: setup
    - role: datadog.datadog
      tags: deploy

  tasks:
    - name: Install system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true
      tags: setup
    
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: setup

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags: setup

    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes
      tags: setup

    - name: Install Docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      tags: setup

    - name: Ensures /var/tmp/redmine exists
      file:
        path: "/var/tmp/redmine"
        state: directory
      tags: deploy

    - name: Copy env file
      ansible.builtin.template:
        src: .env.example
        dest: "/var/tmp/redmine/.env"
      tags: deploy
    
    - name: Start redmine application
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports:
          - "80:3000"
        env_file: /var/tmp/redmine/.env
      tags: deploy