- hosts: all
  become: yes
  tasks:
    - name: Ensures /var/tmp/redmine exists
      file:
        path: "/var/tmp/redmine"
        state: directory

    - name: Copy env file
      ansible.builtin.template:
        src: .env.example
        dest: "/var/tmp/redmine/.env"
    
    - name: Start redmine application
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports:
          - "80:3000"
        env_file: /var/tmp/redmine/.env