db_host: rc1b-aizt4qo2qcbpm13z.mdb.yandexcloud.net
db_port: 6432
db_user: user1
db_name: db1
db_password: "{{ vault_db_password }}" 

datadog_site: "datadoghq.eu"
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Redmine app server
        url: "http://{{ ansible_host }}"
        timeout: 1
        method: get